BASE_URL = "https://qa-stellarburgers.education-services.ru"
MAIN_PAGE_URL = f"{BASE_URL}/"
LOGIN_URL = f"{BASE_URL}/login"
FORGOT_PASSWORD_URL = f"{BASE_URL}/forgot-password"
RESET_PASSWORD_URL = f"{BASE_URL}/reset-password"
PROFILE_URL = f"{BASE_URL}/account/profile"
ORDER_HISTORY_URL = f"{BASE_URL}/account/order-history"
FEED_URL = f"{BASE_URL}/feed"

REGISTER_USER_API = f"{BASE_URL}/api/auth/register"
LOGIN_USER_API = f"{BASE_URL}/api/auth/login"
USER_API = f"{BASE_URL}/api/auth/user"
INGREDIENTS_API = f"{BASE_URL}/api/ingredients"
ORDERS_API = f"{BASE_URL}/api/orders"
